### ISSUE TITLE
Diagrams with more than 6 sets

### ISSUE THREAD

**Issue by mbernste** [vqf/nVenn#2]
Hi,  Does this tool support creating diagrams for more than 6 sets? I notice that the web interface only supports 6 so I tried to use the command line tool, but the program hit a segmentation fault whenever I fed the program more than 6 sets.  Is there a way to run the command line tool to generate diagrams for more than 6?

Thanks!

**Comment by vqf** [comment]
In principle, the code sets no limit to the number of sets. Segmentation faults may arise from bugs in the code. Could you please post the content of the input file so that I can see and debug the issue?
Thanks

**Comment by vqf** [comment]
Dear Matthew,
I have no experience with this system, so I answered at Github and I and also sending it by mail:

In principle, the code sets no limit to the number of sets. Segmentation faults may arise from bugs in the code. Could you please post (or send) the content of the input file so that I can see and debug the issue?
Thanks

Victor


De: Matthew Bernstein [mailto:notifications@github.com]
Enviado el: viernes, 30 de noviembre de 2018 5:22
Para: vqf/nVenn <nVenn@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [vqf/nVenn] Diagrams with greater than 6 sets (#2)


Hi, Does this tool support creating diagrams for more than 6 sets? I notice that the web interface only supports 6 so I tried to use the command line tool, but the program hit a segmentation fault whenever I fed the program more than 6 sets. Is there a way to run the command line tool to generate diagrams for more than 6?

Thanks!

**Comment by mbernste** [comment]
Thank you for your help. I have attached my input file.
[input_venn_8_sets.txt](https://github.com/vqf/nVenn/files/2634349/input_venn_8_sets.txt)

**Comment by vqf** [comment]
The input has an issue that leads to a segmentation fault. The first number corresponds to the 00000000 set, which should always be zero. Assuming that 3480 is the number of elements in set1, the beginning of the file should be:

nVenn v1.1
8
hematopoietic cell
embryonic cell
precursor cell
neural cell
germ line cell
epithelial cell
connective tissue cell
other
0
3480
129
91
0
597
…

I can patch the code to avoid this issue in future versions. In the meantime, you can edit the input file or use the feed_venn.pl script to generate the input file. I hope this helps. I am attaching the svg file when the input file is edited. It takes about five cycles of nVenn.exe
De: Matthew Bernstein [mailto:notifications@github.com]
Enviado el: viernes, 30 de noviembre de 2018 18:22
Para: vqf/nVenn <nVenn@noreply.github.com>
CC: vqf <quesadavictor@uniovi.es>; Comment <comment@noreply.github.com>
Asunto: Re: [vqf/nVenn] Diagrams with more than 6 sets (#2)


Thank you for your help. I have attached my input file.
input_venn_8_sets.txt<https://github.com/vqf/nVenn/files/2634349/input_venn_8_sets.txt>

**Comment by mbernste** [comment]
Thank you again for your help. Unfortunately, I am still receiving a segmentation fault even when I use the output of feed_venn.pl.  The issue may be due to the fact that the binary is not compatible with my machine. Do you know how I can go about compiling the code from source for Linux?

**Comment by vqf** [comment]
Please, make sure that the input is correct. As shown in the Readme, feed_venn.pl outputs a header that must be deleted. If you are not sure how to do that, use the feed_venn_noheader.pl file I just uploaded. The output of that script can be used directly.

If you want to re-compile the binary, you can just run in the source folder:

g++ -Wall main.cpp -o nVenn



De: Matthew Bernstein [mailto:notifications@github.com]
Enviado el: sábado, 1 de diciembre de 2018 18:33
Para: vqf/nVenn <nVenn@noreply.github.com>
CC: vqf <quesadavictor@uniovi.es>; Comment <comment@noreply.github.com>
Asunto: Re: [vqf/nVenn] Diagrams with more than 6 sets (#2)


Thank you again for your help. Unfortunately, I am still receiving a segmentation fault even when I use the output of feed_venn.pl. The issue may be due to the fact that the binary is not compatible with my machine. Do you know how I can go about compiling the code from source for Linux?

**Comment by mbernste** [comment]
When I run the binary file in this repository I still get a seg fault with 8 sets; however, when I compile the code myself it looks to work. Thanks!

One more question, my result does not look quite right (see attached image).  Do you know what the issue might be? You mentioned that the program required 5 cycles. To run 5 cycles, is there something I need to change about how I run the program? Thanks again.

<img width="686" alt="screen shot 2018-12-01 at 12 55 59 pm" src="https://user-images.githubusercontent.com/5004419/49331822-bc56a900-f568-11e8-93c6-b31fd6a8d6df.png">

**Comment by vqf** [comment]
The result should be saved. Simply run the program repeatedly and the diagram will improve.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mbernste** [comment]
Thank you, I am now getting good results. I appreciate all of your help with this and I look forward to making beautiful figures with nVenn.
